# Generated by Django 5.2.7 on 2025-10-20 23:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_sugestaouser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sugestaouser',
            options={'verbose_name': 'Sugestão de Usuário', 'verbose_name_plural': 'Sugestões de Usuários'},
        ),
        migrations.RenameField(
            model_name='sugestaouser',
            old_name='data_da_sugestao',
            new_name='data_criacao',
        ),
        migrations.AlterField(
            model_name='sugestaouser',
            name='texto',
            field=models.TextField(verbose_name='Texto da Sugestão'),
        ),
        migrations.AlterField(
            model_name='sugestaouser',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário (opcional)'),
        ),
    ]
