# Generated by Django 5.2.7 on 2025-12-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0005_programaradio'),
    ]

    operations = [
        migrations.AddField(
            model_name='programaradio',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='programas_radio/'),
        ),
    ]
