# Generated by Django 5.2.6 on 2025-12-08 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0006_programaradio_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to='capas_noticias/'),
        ),
    ]
