# Generated by Django 5.2.6 on 2025-12-08 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0007_noticia_capa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='capa',
        ),
        migrations.AddField(
            model_name='noticia',
            name='imagem_capa_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
